class homepageselectors:
    select_site_btn="/html/body/span[1]/div[1]/span/div[1]/div[2]/span/div/button"
    site_xpath="/html/body/span[1]/div[1]/span/div[1]/div[2]/span/div/div/a[1]"
    step1_heading="/html/body/span[1]/div[1]/span/div[1]/div[2]/span/div/h5"
    v2_membership_btn="/html/body/span[1]/div[1]/span/div[2]/div[2]/span/div/div/div/div[3]/div/div/button"
    membership_btn1="/html/body/span[1]/div[1]/span/div[2]/div[2]/span/div/div[1]/div/div[3]/div/div/button"
    membership_btn2="/html/body/span[1]/div[1]/span/div[2]/div[2]/span/div/div[2]/div/div[3]/div/div/button"
    monthly_mem_btn="/html/body/span[1]/div[1]/span/div[3]/div[2]/span/div/div/a[2]"
    step2_heading="/html/body/span[1]/div[1]/span/div[2]/div[2]/span/div/h5"
    payment_btn="/html/body/span[1]/div[1]/span/div[3]/div[2]/span/div/button"
    step3_heading="/html/body/span[1]/div[1]/span/div[3]/div[2]/span/h5"
    fiftymem="/html/body/span[1]/div[1]/span/div[2]/div[2]/span/div/div[2]/div/div[3]/div/div/div/a[1]"

class loginselectors:
    login_email="/html/body/span[1]/div[1]/span/div[4]/div[2]/span/div/span/div/div[1]/div/div[1]/div[1]/input"
    login_password="/html/body/span[1]/div[1]/span/div[4]/div[2]/span/div/span/div/div[1]/div/div[1]/div[2]/input"
    login_btn="/html/body/span[1]/div[1]/span/div[4]/div[2]/span/div/span/div/div[1]/div/div[2]/button"
    create_acc_btn="/html/body/span[1]/div[1]/span/div[4]/div[2]/span/div/span/div/div[2]/div/div[2]/button"
    login_heading="/html/body/span[1]/div[1]/span/div[4]/div[2]/span/div/span/div[1]/div[2]/h5"
    continue_btn="/html/body/span[1]/div[1]/span/div[4]/div[2]/span/div/span/div[2]/div/div[1]/button"
    continu2_btn="/html/body/span[1]/div[1]/span/div[5]/div[2]/span/form/div[1]/div[3]/a"
    p1_firstname="/html/body/span[1]/div[1]/span/div[5]/div[2]/span/form/div[1]/div[2]/div[1]/div[1]/div[1]/div/input"
    p1_lastname="/html/body/span[1]/div[1]/span/div[5]/div[2]/span/form/div[1]/div[2]/div[1]/div[1]/div[2]/div/input"
    p1_dob="/html/body/span[1]/div[1]/span/div[5]/div[2]/span/form/div[1]/div[2]/div[1]/div[2]/div/div/span/input"
    p2_firstname="/html/body/span[1]/div[1]/span/div[5]/div[2]/span/form/div[1]/div[2]/div[2]/div[1]/div[1]/div/input"
    p2_lastname="/html/body/span[1]/div[1]/span/div[5]/div[2]/span/form/div[1]/div[2]/div[2]/div[1]/div[2]/div/input"
    p2_dob="/html/body/span[1]/div[1]/span/div[5]/div[2]/span/form/div[1]/div[2]/div[2]/div[2]/div/div/span/input"
    p3_firstname="/html/body/span[1]/div[1]/span/div[5]/div[2]/span/form/div[1]/div[2]/div[3]/div[1]/div[1]/div/input"
    p3_lastname="/html/body/span[1]/div[1]/span/div[5]/div[2]/span/form/div[1]/div[2]/div[3]/div[1]/div[2]/div/input"
    p3_dob="/html/body/span[1]/div[1]/span/div[5]/div[2]/span/form/div[1]/div[2]/div[3]/div[2]/div/div/span/input"
    p4_firstname="/html/body/span[1]/div[1]/span/div[5]/div[2]/span/form/div[1]/div[2]/div[4]/div[1]/div[1]/div/input"
    p4_lastname="/html/body/span[1]/div[1]/span/div[5]/div[2]/span/form/div[1]/div[2]/div[4]/div[1]/div[2]/div/input"
    p4_dob="/html/body/span[1]/div[1]/span/div[5]/div[2]/span/form/div[1]/div[2]/div[4]/div[2]/div/div/span/input"
    participant_firstname="/html/body/span[1]/div[1]/span/div[5]/div[2]/span/form/div[1]/div[2]/div/div[1]/div[1]/div/input"
    participant_lasttname="/html/body/span[1]/div[1]/span/div[5]/div[2]/span/form/div[1]/div[2]/div/div[1]/div[2]/div/input"
    participant_dob="/html/body/span[1]/div[1]/span/div[5]/div[2]/span/form/div[1]/div[2]/div/div[2]/div/div/span/input"
    participant_error_message="/html/body/span[1]/div[1]/span/div[5]/div[2]/span/form/div[1]/div[2]/span/div/div"
    summary_heading="/html/body/span[1]/div[1]/span/div[6]/div[2]/span/div[1]/div[1]/h4"
    create_acc_btn="/html/body/span[1]/div[1]/span/div[4]/div[2]/span/div/span/form/div[2]/div/div[1]/a"
    signup_firstname="/html/body/span[1]/div[1]/span/div[4]/div[2]/span/div/span/form/div[1]/div/div[1]/div[1]/div/input"
    signup_lastname="/html/body/span[1]/div[1]/span/div[4]/div[2]/span/div/span/form/div[1]/div/div[1]/div[2]/div/input"
    signup_email="/html/body/span[1]/div[1]/span/div[4]/div[2]/span/div/span/form/div[1]/div/div[1]/div[4]/div/input"
    signup_phone="/html/body/span[1]/div[1]/span/div[4]/div[2]/span/div/span/form/div[1]/div/div[1]/div[5]/div/input"
    signup_dob="/html/body/span[1]/div[1]/span/div[4]/div[2]/span/div/span/form/div[1]/div/div[1]/div[3]/div/input"
    signup_password="/html/body/span[1]/div[1]/span/div[4]/div[2]/span/div/span/form/div[1]/div/div[1]/span/div/div/input"
    street="/html/body/span[1]/div[1]/span/div[4]/div[2]/span/div/span/form/div[1]/div/div[2]/div[1]/div/textarea"
    postcode="/html/body/span[1]/div[1]/span/div[4]/div[2]/span/div/span/form/div[1]/div/div[2]/div[4]/div/input"
    town="/html/body/span[1]/div[1]/span/div[4]/div[2]/span/div/span/form/div[1]/div/div[2]/div[2]/div/input"
    city="/html/body/span[1]/div[1]/span/div[4]/div[2]/span/div/span/form/div[1]/div/div[2]/div[3]/div/input"

class paymentselector:
    cardholder="/html/body/span[1]/div[1]/span/div[6]/div[2]/span/span/div/div[2]/div/div/form/div[1]/div/input"
    cardnumber="/html/body/span[1]/div[1]/span/div[6]/div[2]/span/span/div/div[2]/div/div/form/div[2]/div/input"
    expirymonth="/html/body/span[1]/div[1]/span/div[6]/div[2]/span/span/div/div[2]/div/div/form/div[3]/div/div/div[1]/select"
    expiryyear="/html/body/span[1]/div[1]/span/div[6]/div[2]/span/span/div/div[2]/div/div/form/div[3]/div/div/div[2]/select"
    cv2="/html/body/span[1]/div[1]/span/div[6]/div[2]/span/span/div/div[2]/div/div/form/div[4]/div/input"
    pay_btn="/html/body/span[1]/div[1]/span/div[6]/div[2]/span/span/div/div[3]/span/div/button"

class successpageselectors:
    success_heading="/html/body/span[1]/div[1]/span/div/div[1]/h2"
    mem_type="/html/body/span[1]/div[1]/span/div/div[2]/div[1]/div[2]/div[1]/div[2]/p"
    member_name="/html/body/span[1]/div[1]/span/div/div[2]/div[2]/div[2]/div/div/table/tbody/tr/td[1]"

class bookingpageselectors2:
    booking_btn="/html/body/div[2]/div/div[3]/form/div[2]/div/div[1]/div/input"
    mem_prod_btn="/html/body/div[2]/div/span[1]/span/span[1]/span/div[1]/div/span/form/input[2]"
    membership_product="/html/body/div[2]/div/span[1]/span/span[1]/span/div[1]/div/ul/li"
    