class commonpath:
    path ="/home/bnuser/Documents/TestScripts-main/chromedriver"

class homepageselector:
    booking_date="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/lightning-input/lightning-datepicker/div/div/input"
    booking_time="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[2]/div/lightning-input/lightning-timepicker/div/lightning-base-combobox/div/div[1]/input"
    no_of_bays="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[3]/div/div/div/div/select"
    site_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[4]/div/div/div/div/select"
    modal_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[2]"
    date_xpath= "/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div[1]/div/div[2]/div/div[1]/div/lightning-input/lightning-datepicker/div/div/input"
    calendar_tbody="/html/body/div[3]/div[2]/div/div[2]/div/div/div[2]/div[1]/div/lightning-input/lightning-datepicker/div/div/lightning-calendar/div/table/tbody"
    calendar_button='/html/body/div[3]/div[2]/div/div[2]/div/div/div[2]/div[1]/div/lightning-input/lightning-datepicker/div/div/lightning-button-icon'
    time_xpath= "/html/body/div[3]/div[2]/div/div[2]/div/div/div[2]/div[2]/div/lightning-input/lightning-timepicker/div/lightning-base-combobox/div/div[1]/input"
    guest_xpath= '/html/body/div[3]/div[2]/div/div[2]/div/div/div[2]/div[3]/div/div/div/div/select'
    venue_name = "selectedSite"
    next_step_xpath= "/html/body/div[3]/div[2]/div/div[2]/div/div/div[2]/div[5]/div/button/span"
    next_step2_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[5]/div/button/span"

class productpageselectors:
    title_date="/html/body/div[3]/div[2]/div/div[2]/div/div/header/div/section[1]/span/i/lightning-formatted-date-time"
    date_xpath= "/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div/div[3]/div/div[2]/div/div[1]/div/lightning-input/lightning-datepicker/div/div/input"
    date2_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div/div[2]/div/div[2]/div/div[1]/div/lightning-input/lightning-datepicker/div/div/input"
    date_xpath3="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div/div[1]/div/div[2]/div/div[1]/div/lightning-input/lightning-datepicker/div/div/input"
    adult_selection_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div/div[3]/div/div[2]/div/div[2]/div/div/div/div/select"
    adult_selection2="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div/div[2]/div/div[2]/div/div[2]/div/div/div/div/select"
    adult_selection_xpath2="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div/div[1]/div/div[2]/div/div[3]/div/div/div/div/select"
    adult_selection_name="Adults"
    adult_selection4="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div/div[4]/div/div[2]/div/div[2]/div/div/div/div/select"
    guest_age="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div/div[1]/div/div[2]/div/div[2]/div/div/div/div/select"
    search_button_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div/div[1]/div/div[2]/div/button"
    search_button_xpath2="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div/div[2]/div/div[2]/div/button/span"
    search_button_xpath3="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div/div[3]/div/div[2]/div/button/span"
    search_button_xpath4="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div/div[4]/div/div[2]/div/button"
    promocode_field="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[2]/div/div[2]/div/div[2]/lightning-input/div/input"
    add_promocode_button="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[2]/div/div[2]/div/div[3]/button"
    add_on_name1="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div[3]/div/div/div[1]/div[2]/h2"
    promocode_error="/div/div/div/div/div"
    total_value="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[2]/div/div[2]/div/div[1]/table/tr[3]/td[3]/lightning-formatted-number"
    back_to_group="/html/body/div[3]/div[2]/div/div[2]/div/div/header/div/section[1]/button"
    
class bookingselectors:
    select_option_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div[1]/div/div/div[1]/div[3]/div/div/select"
    add_quantity_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div[3]/div/div/div[2]/div[2]/button[2]"
    add_to_cart_button_xpath= "/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/nav/div/div/div[2]/button"
    proceed_to_cart_xpath= "/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[2]/div/div[2]/div/div[4]/button/span"
    accept_terms_button_xpath ="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/nav/div/div/div[2]/button/span"
    total_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[2]/div/div[2]/div/div[1]/table/tr[3]/td[3]"
    
class loginselectors:
    payment_method_label="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/header/div/section[1]/span"
    reset_password="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[2]/div/div/div/div[2]/div/button[2]"
    logged_in_heading="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[2]/div/div/div/div[1]/div[2]/h2"
    forgot_password="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[2]/div[4]/div/button"
    loginhere_email="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[2]/div[1]/div/lightning-input/div[1]/input"
    loginhere_password="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[2]/div[2]/div/lightning-input/div/input"
    loginhere_button="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[2]/div[3]/div/button"
    logged_in_as_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/header/div/section[2]/button"
    login_label_text="/html/body/div[3]/div[2]/div/div[2]/div/div/header/div/section[2]/button"
    login_email1="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div[1]/div/lightning-input/div[1]/input"
    login_password1="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div[2]/div/lightning-input/div/input"
    login_button_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div[3]/div/button/span"
    login_firstname_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div[1]/lightning-input/div[1]/input"
    login_lastname_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div[2]/lightning-input/div/input"
    login_email_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div[3]/lightning-input/div/input"
    login_phone1_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div[4]/lightning-input/div/input"
    login_phone_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div[5]/lightning-input/div/input"
    login_password_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div[8]/lightning-input/div/input"
    login_dob_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div[4]/lightning-input/lightning-datepicker/div/div/input"
    new_cust_name="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/header/div/section[2]/button"

class paymentselectors:
    share_payment_name_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/section[1]/div/div/div[2]/div/div[2]/div[2]/lightning-input/div[1]/input"
    share_payment_email_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/section[1]/div/div/div[2]/div/div[3]/div[2]/lightning-input/div/input"
    remove_button_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/section[1]/div/div/div[2]/div/div[4]/div/button"

    name_on_card_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div/div/div/div/h3/div/div[2]/lightning-input/div/input"
    card_number_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div/div/div/div/h3/div/div[5]/lightning-input/div/input"
    expiry_month_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div/div/div/div/h3/div/div[8]/div/div/div/select"
    expiry_year_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div/div/div/div/h3/div/div[9]/div/div/div/select"
    security_code="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div/div/div/div/h3/div/div[12]/lightning-input/div/input"
    change_method_xpath = "/html/body/div[3]/div[2]/div/div[2]/div/div/nav/div/div/div[1]/button"  
    card_name="/html/body/form/div[1]/ul/li/div/table/tbody/tr[2]/td[2]/div/input"
    card_number="/html/body/form/div[1]/ul/li/div/table/tbody/tr[3]/td[2]/div/input"
    expiry_month="/html/body/form/div[1]/ul/li/div/table/tbody/tr[4]/td[2]/div/select[1]"
    expiry_year="/html/body/form/div[1]/ul/li/div/table/tbody/tr[4]/td[2]/div/select[2]"
    cvc_num="/html/body/form/div[1]/ul/li/div/table/tbody/tr[5]/td[2]/div/input"
    pay_btn="/html/body/form/div[1]/ul/li/div/table/tbody/tr[6]/td/div/input"


class confirmationpageselectors:
    heading_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div/div/div/div[1]/h2"
    detail_area_xpath= "/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[1]/div/div/div/div[2]"
    cart_area_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/div[1]/div/div/div[2]/div[2]/div/div[2]"
    total_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[1]/table/tr[3]/td[3]/lightning-formatted-number"
    sub_total_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[1]/table/tr[1]/td[3]/lightning-formatted-number"
    vat_xpath="/html/body/div[3]/div[2]/div/div[2]/div/div/div[2]/div[2]/div/div[2]/div/div[1]/table/tr[2]/td[3]/lightning-formatted-number"
    product1_price="/html/body/div[3]/div[2]/div/div[2]/div/div/div[2]/div[1]/div/div/div/div/div[2]/h3[2]/lightning-formatted-number"
    product2_price="/html/body/div[3]/div[2]/div/div[2]/div/div/div[2]/div[1]/div[1]/div/div/div/div[2]/h3[2]/lightning-formatted-number"
    add_on1_price="/html/body/div[3]/div[2]/div/div[2]/div/div/div[2]/div[1]/div[3]/div[1]/div/div[2]/div[1]/div/span/span/span/lightning-formatted-number"
    add_on2_price="/html/body/div[3]/div[2]/div/div[2]/div/div/div[2]/div[1]/div[3]/div[2]/div/div[2]/div[1]/div/span/span/span/lightning-formatted-number"
    product3_price="/html/body/div[3]/div[2]/div/div[2]/div/div/div[2]/div[1]/div[1]/div/div/div/div[2]/h3[2]/lightning-formatted-number"


class filterselectors:
    filter_lines="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/header/div/section[1]/button"
    date="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/aside/div/div/div[2]/lightning-input/lightning-datepicker/div/div/input"
    location="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/aside/div/div/div[2]/div[1]/div/div/select"
    quantity_num="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/aside/div/div/div[2]/div[2]/div/div/lightning-input/div/input"
    min_price="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/aside/div/div/div[2]/div[3]/div/div[1]/lightning-input/div/input"
    max_price="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/aside/div/div/div[2]/div[3]/div/div[2]/lightning-input/div/input"
    prod_type="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/aside/div/div/div[2]/div[4]/div/div/select"
    apply_btn="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/aside/div/div/div[2]/div[6]/button"
    pro_date="/html/body/div[3]/div[2]/div/div[2]/div/div/div[3]/header/div/section[1]/span/i/lightning-formatted-date-time"
